# Generated by Django 3.1.7 on 2021-02-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('Category', models.CharField(default='', max_length=50)),
                ('Sub_Category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('product_Desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='media')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
