# Generated by Django 3.1.6 on 2021-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocal', '0002_homemakeover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemakeover',
            name='img',
            field=models.ImageField(upload_to='Home'),
        ),
    ]
