# Generated by Django 3.1.6 on 2021-02-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocal', '0003_auto_20210227_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Home')),
                ('price', models.IntegerField(default=0)),
                ('offer', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'BeautyProduct',
            },
        ),
    ]
