# Generated by Django 3.1.6 on 2021-03-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocal', '0006_stationary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautyproduct',
            name='img',
            field=models.ImageField(upload_to='Beauty'),
        ),
        migrations.AlterField(
            model_name='sanityware',
            name='img',
            field=models.ImageField(upload_to='Sanitry'),
        ),
        migrations.AlterField(
            model_name='stationary',
            name='img',
            field=models.ImageField(upload_to='Stationary'),
        ),
    ]
