# Generated by Django 3.1.6 on 2021-03-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocal', '0007_auto_20210301_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyproduct',
            name='desc',
            field=models.TextField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='homemakeover',
            name='desc',
            field=models.TextField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='sanityware',
            name='desc',
            field=models.TextField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='stationary',
            name='desc',
            field=models.TextField(default=0, max_length=250),
        ),
    ]
